#+TITLE: Grammar Docs
#+DESCRIPTION: Notes on grammar in the english language
#+AUTHOR: Cassette
#+DATE: 2022-11-01
#+STARTUP: showall

* Grammar is a set of rules that defines the structure of sentances within a language

** Nouns
 A Noun is a word that functions as a name or title of a thing
 - Singular Noun :: A Singular Noun is a noun that refers to one thing
 - Plural Nouns :: A Plural Noun is a noun that refers to several things
 - Irregular Plural Nouns :: Not all Plural Nouns are a simple modification of a Singular Noun. Some Plural Nouns are a different word from the singular, such as Child - Children, not Childs.
 - Common Noun :: A Common Noun is a noun refering to a relativly broad class of things, as opposed to a specifc thing. Such as Mother. Common Nouns are capitalised when they are at the start of a sentence.
 - Proper Noun :: A Proper Noun is a coun refering to a specific thing, such as Jessica, which may be the name of your mother. A Proper Noun is always capitalised (in most forms of English)
 - Concrete Noun :: A Concrete Noun refers to a physical or "real" thing, such as a tree or a person.
 - Abstract Noun :: An Abstract Noun refers to a non-physical thing, such as sadness or freedom.

*** Adjectives
  Adjectives are nouns that describe a thing.
 
  Adjective Order
  In English, adjectives are put in a specific order.
  - Determiner
  - Opinion
  - Size
  - Age
  - Shape
  - Colour
  - Origin
  - Material
  - Purpose

** Verbs
 A Verb is a word that conveys or expresses an action, occurence, or state of being. IE: Run[s], Sleep[s]. Many words can be both nouns and verbs. IE: "I go for a run every day", run is a noun. "The dog ran across the park:, run is a verb

 - Verb Tenses :: A Verb Tense is the catagory of time in which a verb refers to. The English language has three tenses; past, present, and future. IE: Ran, Running, Will Run.
 - Helping Verb :: A Helping Verb is a verb used along side a verb, used to express the main verb's tense, mood, or voice. IE: To have, To be, To do. 
 - Linking Verbs :: A Linking Verb is a verb used to connect the subject(noun) with more information about the subject. IE: Is. "The person Is hungry" linking "person" and "hungry".
 - Modal Verb :: A Modal Verb is a verb that defines the Modality, whether or not something is likly or certain to happen, if it's possible, if you should, if you have permission. IE: May, Should, Will, Can. These verbs can be attatched to any subject in the same way. IE: "You can", "She can", "You should", "She should", "They will", "I must".
 - Irregular Verb :: An Irregular Verb is a verb that significantly changes the whole word in different tenses, like Irregular Nouns.
 - Verb Aspect :: The Verb Aspect is simialr to Verb Tense, but with a finer control over the context of the verb.
 - Simple Aspect :: The Simple Aspect is the tense of the verb
 - Progressive Aspect :: The Progressive Aspect refers to things that are on-going, currently happening. Often changes words into their "-ing" versions in English. IE: "I walk" to "I am walking".
 - Perfect Aspect :: The Perfect Aspect refers to things that are complete, it can be thought of as a tense between past and present. IE: "I have walked today". You can also use Perfect Aspect in Past Tense though, with "I had gone on a walk", as opposed to "I walked" which is the 'normal' Past Tense. "I will have walked" is also the Future Tense Perfect Aspect.
 - Perfect Progressive Aspect :: The Perfect Progressive Aspct refers to things that you have been, had been, or will be doing for a long time. IE: "I had been eating for ten years", "I have been eating for ten years", "I will have been eating for ten years"
 - Adjective :: An Adjective is a word that modifies a noun and gives infomation about the subject. IE: "the bear", "the Blue bear".
 - Article :: An Article is a word used to indicate whether a noun is specific or not. IE: "A person", "The person".
 - Definite and Indefinite Article :: A Definite Article is an article that implies that the thing in context is already known. IE: "Can I please have The meal". An INdefinite Article refers to any thing within a group. IE: "Can I please have A meal".

*** Adverb
  An Adverb is a word that modifies a verb, technically anything that isnt a noun. IE: "They ran *Slowly*", "We slept *Terribly*". Adverbs can also modify adjectives. IE: "She was Very hungry" Very is modifiying Hungry.


