#+TITLE: Linguistics Notes
#+DESCRIPTION: Notes on the study of linguistics
#+AUTHOR: Cassette
#+DATE: 2022-11-01
#+STARTUP: showall

* Linguistics is the study of language and how it works

- Sociolinguistics :: The study of language in the context of social situations and society
- Historical Linguistics :: The study of langauges across and in reference to history
- Psycholinguistics :: The study of language as it relates to the brain
- Meta-Linguistic Awareness :: The ability to consciously reflect on the nature of langauge

Language exists at two levels. The level of the Form, and the level of the Combination of Forms
- Forms :: The sounds or shapes used, which don't have inherent meaning
- Combinaiton of Forms :: The synthesis of forms used to create meaning

A Sign is anything that conveys meaning beyond itself. "rain" and the smell of moisture in the air can both be signs of rain. A sign can also refer to the literal hand-sign used in signed language
- Arbitrariness of the Sign :: Refering to the fact that a Sign has no inherent reason to be the thing it is. A person could've pointed at a rock and said "rain" and it would've been just as valid.

- Displacement :: The ability to talk about things that are beyond the here and now, both in space and in time.
- Reflexivity :: The ability to use language to talk about language

Phonetics is the study of individual sounds in spoken langauges, or handshapes in singed languages

Phonology is the study of how individual sounds or handshapes are combined into specfic patterns

Morphology is the study of the internal structure of words

Syntax is the study of how words group together to make sentences

Semantics is the study of meanings of words and sentences

Pragmatics is the study of meanings of words and sentences in a larger social context
