#+TITLE: Philosophy
#+DESCRIPTION: Notes on philosophy
#+AUTHOR: Cassette
#+DATE: 2022-11-01
#+STARTUP: showall

* To be a philosopher is to have a love for wisdom

The word "Philosophy" has roots in ancient Greece, stemming from the word "Philosophia". It is a combination of "Philos", which can mean "love", and "Sophos", which can mean "wise" or "wisdom". Literally, a lover of wisdom. 

To have "wisdom" or to be "wise" is more than knowing stuff. To be wise is to be able to apply knowledge with intuition and nuance to practical use, often without the need for external help. For example; you can be very knowledgeable in an instrument, but you can't be wise in said instrument. You can, however, be a wise musician, knowing when and how to apply your musical skills. An unwise professional guitar player would be the type to randomly play at parties without being prompted by anyone.

In its earliest uses, Philosophy was used to roughly mean "the study of anything". Ancient Greek philosophers studied math, physics, poetry, music, politics, and many other subjects. As academia developed and the concept of science and [[STEM]] was created, philosophy began to be defined as "thinking about questions". A definition that still holds true today.

** Branches of philosophy
 There are three main branches of philosophy, with two subsections in **value theory**. These are categories that questions and schools of thought fall into.

 The three branches are:

 | Branch name  | Definition                                                  |
 |--------------+-------------------------------------------------------------|
 | Meta physics | The study of reality and the nature of reality              |
 | Epistemology | The study of knowledge, what is "true" and what is not      |
 | Value Theory | Divided into two subsections. Ethics and Aesthetics         |
 | Ethics       | The study of human conflict, of what is "right" and "wrong" |
 | Aesthetics   | The study of beauty and art                                 |


*** Logic 
 Logic is the main tool of philosophy. It assists in making arguments and giving reason. A **Fallacy** is when an argument is unreasonable or unsound.
